[greenclip]
history_file = "/home/arsham/Dropbox/Home/.cache/greenclip.history"
max_history_length = 50000
max_selection_size_bytes = 0
trim_space_from_selection = true
use_primary_selection_as_input = true
blacklisted_applications = []
enable_image_support = false
image_cache_directory = "/tmp/greenclip"
static_history = [
 '''¯\_(ツ)_/¯''',
]
