#!/bin/bash

# Shows failed pods.
# Usage:
#    k dirty [-c=CONTEXT] [-n=NAMESPACE]
#
# By default it shows all failed pods from all namespaces in the current
# context.

_namespace="--all-namespaces"
_context=""

for ARGUMENT in "$@"
do
    KEY=$(echo $ARGUMENT | cut -f1 -d '=')
    VALUE=$(echo $ARGUMENT | cut -f2 -d '=')

    case "$KEY" in
        --namespace|-n)      _namespace="-n ${VALUE}" ;;
          --context|-c) _context="--context ${VALUE}" ;;
        *)
        echo "Unrecognised option ${KEY}"
        exit 1
        ;;
    esac

done

kubectl get po $_context $_namespace -o="custom-columns=NAME:.metadata.name,READY:.status.containerStatuses[*].ready,PHASE:.status.phase,RESTARTS:.status.containerStatuses[*].restartCount" --field-selector=status.phase=Failed

# vim: ft=zsh:nowrap
