#!/bin/bash

_context=""
if [[ "$1" ]]; then
    _context="--context $1"
fi

kubectl get $_context nodes -L beta.kubernetes.io/instance-type,kops.k8s.io/instancegroup,failure-domain.beta.kubernetes.io/zone
