#!/bin/bash

if [ -z "$1" ]; then
    kubectl get po --all-namespaces | awk '{split($3,a,"/"); if (a[1] != a[2] && $4 != "Completed"){print $0}}'
else
    kubectl get po -n $1 | awk '{split($2,a,"/"); if (a[1] != a[2] && $3 != "Completed"){print $0}}'
fi

