#!/bin/zsh
#
# Shows the list of commits from the given sub-command and opens in vim
# when you select one.

local range="--all"
if [ $# -gt 1 ]; then
    range="${@:2}"
fi

local format=$(echo "%H\t%C(yellow)%h%C(red)%C(reset)\t%C(bold green)(%ar)%C(reset)\t%s\t%C(green)<%an>%C(reset)\t%C(blue)%d%C(reset)" | sed 's/\t/%x09/g')
git $1 --decorate --format=format:"$format" --color=always $range |
    fzf --ansi --no-sort --preview-window nohidden +m \
        --delimiter "\t" --nth 3.. --with-nth 2.. \
        --preview "echo {} | grep -o '[a-f0-9]\{7\}' | head -1 |
                    xargs -I % sh -c 'git show --color=always %'" \
        --bind "enter:execute:echo {} |
                grep -o '[a-f0-9]\{40\}' | head -1 |
                xargs -I % sh -c '$EDITOR fugitive://\$(git rev-parse --show-toplevel)/.git//% < /dev/tty'"

# vim: ft=zsh:nowrap
