#!/bin/zsh
# Grep in all commits and open the editor for the selection.
# Usage: git rev-grep <pattern>

local term=$1
if [ -z $1 ]; then
    term="''"
fi

local format=$(echo "%H\t* %h\t%ar\t%an\t%s\t%d" | sed 's/\t/%x09/g')
git --no-pager log -G $term --format=format:"$format" |
    fzf --ansi --no-sort --preview-window nohidden +m --exit-0 \
        --header="<Alt-Enter>:Reload on current query" \
        --phony \
        --header-lines=1 \
        --delimiter "\t" \
        --with-nth 3.. --nth 2.. \
        --preview "echo {} | grep -o '[a-f0-9]\{7\}' | head -1 |
                    xargs -I % sh -c 'git show --color=always %'" \
        --bind "change:reload:git --no-pager log -G {q} --format=format:'$format'" \
        --bind "alt-enter:unbind(change,alt-enter)+change-prompt(2. FZF> )+enable-search+clear-query" \
        --bind "enter:execute:echo {} |
                grep -o '[a-f0-9]\{40\}' | head -1 |
                xargs -I % sh -c '$EDITOR fugitive://\$(git rev-parse --show-toplevel)/.git//% < /dev/tty'"

# vim: ft=zsh:nowrap
