#!/bin/zsh
#
# Shows the list of commits and opens in vim when you select one.

local format=$(echo "%H\t%C(yellow)%h%C(red)%C(reset)\t%C(bold green)(%ar)%C(reset)\t%s\t%C(green)<%an>%C(reset)\t%C(blue)%d%C(reset)" | sed 's/\t/%x09/g')
git log --decorate --format=format:"$format" --all --color=always |
    fzf --ansi --no-sort --preview-window nohidden +m \
        --delimiter "\t" --nth 3.. --with-nth 2.. \
        --preview "echo {} | grep -o '[a-f0-9]\{7\}' | head -1 |
                    xargs -I % sh -c 'git show --color=always %'" \
        --bind "enter:execute:echo {} |
                grep -o '[a-f0-9]\{40\}' | head -1 |
                xargs -I % sh -c '$EDITOR fugitive://\$(git rev-parse --show-toplevel)/.git//% < /dev/tty'"

# vim: ft=zsh:nowrap
